//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StepSchedulerEntities : DbContext
    {
        public StepSchedulerEntities()
            : base("name=StepSchedulerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassRooms> ClassRooms { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<ReservedRooms> ReservedRooms { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
