//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.ReservedRooms = new HashSet<ReservedRooms>();
        }
    
        public int RequestId { get; set; }
        public int ClassRoomId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateRequest { get; set; }
        public System.DateTime ClassDate { get; set; }
        public int LessonNumber { get; set; }
        public Nullable<int> CountOfVisitors { get; set; }
        public string EventDescription { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsNew { get; set; }
    
        public virtual ClassRooms ClassRooms { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservedRooms> ReservedRooms { get; set; }
    }
}
