//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedRooms
    {
        public int ReservedRoomId { get; set; }
        public int RequestId { get; set; }
        public int EventType { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
